import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 10 }
dynamic_title = true
opacity = 0.98

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[font]
size = 11.0

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
